### ISSUE TITLE
watch star fork 都用不了

### ISSUE THREAD

**Issue by geekan** [jagt/brogue-chs-translate#1]
watch star fork
都用不了

是github的bug吗……

**Comment by jagt** [comment]
有可能我自己start watch都可以

**Comment by geekan** [comment]
你是不是用git？之前我没用github官方客户端也有这个情况

**Comment by jagt** [comment]
@geekan 的确是的，但这个好没道理啊...

**Comment by geekan** [comment]
@jagt 好了。可以用了。

**Comment by jagt** [comment]
@geekan 恩试着编译下看看 我只在自己机器上试过

**Comment by geekan** [comment]
之前为了作弊已经编译过了，跑起来没问题。
就是当时从cygwin切到mingw有点折腾

makefile看得不是很懂

**Comment by geekan** [comment]
对了，把DEBUG宏换成个开关，一样做成按键触发，测试效率应该会高些

**Comment by jagt** [comment]
@geekan  makefile 我乱拼起来的.. 我短期内不准备再改了 如果那个clight的版本升到1.7.3就准备再试试 现在这个情况要是想升上去太难了...

**Comment by geekan** [comment]
@jagt good luck，你是学生吗？

**Comment by jagt** [comment]
@geekan 已经上班了

**Comment by geekan** [comment]
@jagt 挺有心啊，我之前做过另一个游戏的汉化，不过现在也没什么时间了。

我看你js用比较多，是搞前端的吗？

**Comment by jagt** [comment]
@geekan 我工作做的比较杂.. 有微博么加一个 我的 @jagttt 这边聊太奇怪了
